---
title: "PedPanCancerAugustin"
output: html_document
---

# PACKAGES
```{r}
pacman::p_load(tidyverse, rio, labelled)
pacman::p_load(gt, gtsummary)
?pacman::p_load(bstfun)
pacman::p_load(survival, ggsurvfit)
```
# IMPORT
```{r}
dd <- import ("/Users/sunitasridhar/Desktop/Research/pedpancan/combinedsurv.xlsx") %>% 
   mutate(ecDNA = factor(ecDNA, labels = c('No','Yes')),
          Cancer_Type_Abbrev = factor(Cancer_Type_Abbrev))
```
# LABEL
```{r}
var_label(dd) <- list(Cancer_Type_Abbrev = 'Cancer Type')
```

# DEFINITIONS
# 1 is death (event)     | R 1: Uncensored observation (event occurred)
# 0 is alive  (censored) | R 0: Censored observation.

theme_gtsummary_compact()

## Setting theme `Compact`

# TABLE 1 BY ecDNA
```{r}
dd %>% 
   tbl_summary(by = ecDNA,
               include = c(Cancer_Type_Abbrev, OS_Months, OS_Status),
               sort = list(Cancer_Type_Abbrev ~ 'frequency')) %>% 
   add_overall() %>% 
   add_p( test = list(Cancer_Type_Abbrev ~ 'chisq.test'),
          pvalue_fun = function(x) style_pvalue(x, digits = 2) )
```
# TABLE 1 BY OS_Status
```{r}
dd %>% 
   mutate(OS_Status = factor(OS_Status, labels = c('0-Alive','1-Death'))) %>% 
   tbl_summary(by = OS_Status,
               include = c(Cancer_Type_Abbrev, OS_Months, ecDNA),
               sort = list(Cancer_Type_Abbrev ~ 'frequency')) %>% 
   add_overall() %>% 
   add_p( test = list(Cancer_Type_Abbrev ~ 'chisq.test'),
          pvalue_fun = function(x) style_pvalue(x, digits = 2) )
```
# TABLE 1 (SUBSET)
```{r}
id <- dd %>%
   filter(ecDNA == 'Yes') %>% 
   count(Cancer_Type_Abbrev) %>%
   arrange(desc(n)) %>% 
   filter(n > 4) %>% pull(Cancer_Type_Abbrev)

dd %>% 
   filter(Cancer_Type_Abbrev %in% id) %>% 
   droplevels() %>% 
   tbl_summary(by = ecDNA,
               include = c(Cancer_Type_Abbrev, OS_Months, OS_Status),
               sort = list(Cancer_Type_Abbrev ~ 'frequency')) %>% 
   add_overall() %>% 
   add_p( test = list(Cancer_Type_Abbrev ~ 'chisq.test'),
          pvalue_fun = function(x) style_pvalue(x, digits = 2) )
# MODEL 1
m1 <- coxph(Surv(OS_Months, OS_Status) ~ ecDNA + strata(Cancer_Type_Abbrev), data = dd)

m1 %>% 
   tbl_regression(
      exponentiate = TRUE,
      pvalue_fun = function(x) style_pvalue(x, digits = 2) 
   ) %>% 
   add_inline_forest_plot( 
      spec_pointrange.args = list(
         vline = 1,
         xlim = c(0, 10)
      )
   )
# MODEL 2: INTERACTION
dd %>% 
   expand(OS_Status, ecDNA, Cancer_Type_Abbrev) %>% 
   left_join(dd %>% 
                count(OS_Status, ecDNA, Cancer_Type_Abbrev)
   ) %>% 
   pivot_wider(id_cols = Cancer_Type_Abbrev,
               names_from = c(OS_Status, ecDNA),
               values_from = n) %>% 
   rowwise() %>% 
   mutate(sum = sum(c_across(c(2:5)))) %>% 
   filter(!is.na(sum))

id <- dd %>% 
   expand(OS_Status, ecDNA, Cancer_Type_Abbrev) %>% 
   left_join(dd %>% 
                count(OS_Status, ecDNA, Cancer_Type_Abbrev)
   ) %>% 
   pivot_wider(id_cols = c(Cancer_Type_Abbrev,OS_Status),
               names_from = c(ecDNA),
               values_from = n) %>% 
   rowwise() %>% 
   mutate(sum = sum(c_across(c(3:4)))) %>%
   filter(OS_Status == 1) %>% 
   filter(!is.na(sum)) %>% pull(Cancer_Type_Abbrev)

m2 <- coxph(Surv(OS_Months, OS_Status) ~ ecDNA * strata(Cancer_Type_Abbrev) , 
            data = dd %>% 
               filter(Cancer_Type_Abbrev %in% id ) %>% 
               droplevels() )
m2 %>% 
   tbl_regression(
      exponentiate = TRUE,
      pvalue_fun = function(x) style_pvalue(x, digits = 2)
   ) %>% 
   add_global_p( keep = TRUE ) %>% 
   add_inline_forest_plot( 
      spec_pointrange.args = list(
         vline = 0,
         xlim = c(0, 10),
         xlog = TRUE
      )
   )
```
# SUBGROUP
```{r}
pacman::p_load(partykit)

coxreg <- function(y, x, start = NULL, weights = NULL, offset = NULL, ...) {
   x <- x[, -1]
   coxph(y ~ 0 + x, weights = weights,  ...)
}

m3 <- mob(Surv(OS_Months, OS_Status) ~ ecDNA  | Cancer_Type_Abbrev, 
          data = dd %>% 
             filter(Cancer_Type_Abbrev %in% id ) %>% 
             droplevels(),
          fit = coxreg, 
          control = mob_control(alpha=0.5, bonferroni = FALSE, maxdepth = 2, minsize = 25))


plot(m3)

m3_os <- coxph(Surv(OS_Months, OS_Status) ~ ecDNA , 
               data = dd %>% 
                  filter(Cancer_Type_Abbrev == 'OS' ) %>% 
                  droplevels() ) %>% 
   summary()

# Plot Cox Regression
pacman::p_load(ggsurvfit)

# KM
survfit2( Surv(OS_Months, OS_Status) ~ ecDNA, data = dd ) %>% 
   ggsurvfit() +
   labs(x = 'Follow-up time (Months)',
        y = 'Survival Probability') +
   add_censor_mark(size = 2, alpha = 0.2) +
   add_confidence_interval() +
   add_risktable(risktable_stats = "n.risk") +
   add_risktable_strata_symbol()
```
