---
title: "PedPanCancerSurvAnalysisFullCohort"
output: html_document
last updated: 10-29-2023
---
# DEFINITIONS
# 1 is death (event)     | R 1: Uncensored observation (event occurred)
# 0 is alive  (censored) | R 0: Censored observation.

#load libraries
```{r}
## OSC check that all of these libraries are actually necessary to run this code. 
library(tidyverse)
library(readxl)
library(dplyr)
library("stringr")
library(naniar) #for replace with Nas function
library("survival")
library("survminer")
library(RColorBrewer)
library(janitor)
#library(devtools)
pacman::p_load(tidyverse, rio, labelled)
pacman::p_load(gt, gtsummary)
pacman::p_load(bstfun)
pacman::p_load(survival, ggsurvfit)
pacman::p_load(ggsurvfit)
devtools::install_github("MSKCC-Epi-Bio/bstfun") # Had to install through devtools to get the bstfun package
library(extrafont)
library(svglite)

extrafont::font_import(pattern="Arial",prompt=FALSE)
#extrafont::loadfonts()
```
```{r}
## OSC create an output directory if it doesn't exist
dir.create('../out', showWarnings = FALSE)

load_survival_data <- function(path, filtered){
  ## OSC let's make a function to read in and preprocess the survival table.
  ## You could even parameterize it to subset for cancer types with at least 1 ecDNA+ sample, below.
  combinedsurv <- read_excel(path)
  if(filtered == "ecDNA") {
    combinedsurv <- subset(combinedsurv, Cancer_Type_Abbrev == "ACT" | Cancer_Type_Abbrev == "BT"| 
    Cancer_Type_Abbrev == "CPC" | Cancer_Type_Abbrev == "CPG" | Cancer_Type_Abbrev == "HGG" | 
    Cancer_Type_Abbrev == "EP" | Cancer_Type_Abbrev == "ETMR" | Cancer_Type_Abbrev == "GG" |     
    Cancer_Type_Abbrev == "LGG" | Cancer_Type_Abbrev == "MB" | Cancer_Type_Abbrev == "MPNST" | 
    Cancer_Type_Abbrev == "MST" | Cancer_Type_Abbrev == "NBL" | Cancer_Type_Abbrev == "OS"| 
    Cancer_Type_Abbrev == "PB" | Cancer_Type_Abbrev == "RB" | Cancer_Type_Abbrev == "RHB" | 
    Cancer_Type_Abbrev == "ST")
  }
  if(filtered == "surv_cox") {
    combinedsurv <- subset(combinedsurv, Cancer_Type_Abbrev == "ACT" | Cancer_Type_Abbrev == "BT"| 
    Cancer_Type_Abbrev == "CPC" | Cancer_Type_Abbrev == "CPG" | Cancer_Type_Abbrev == "HGG" | 
    Cancer_Type_Abbrev == "EP" | Cancer_Type_Abbrev == "ETMR" |     
    Cancer_Type_Abbrev == "LGG" | Cancer_Type_Abbrev == "MB" | Cancer_Type_Abbrev == "MPNST" | 
    Cancer_Type_Abbrev == "MST" | Cancer_Type_Abbrev == "NBL" | Cancer_Type_Abbrev == "OS"| 
    Cancer_Type_Abbrev == "PB" | Cancer_Type_Abbrev == "RHB" | 
    Cancer_Type_Abbrev == "ST")
  }
  dd <- combinedsurv %>% 
  mutate(ecDNA = factor(ecDNA_Status, labels = c('No','Yes')),
          Cancer_Type = factor(Cancer_Type_Abbrev))
  var_label(dd) <- list(Cancer_Type = 'Cancer_Type_Abbrev')
  return(dd)
}
cox_plot <- function(data,outfile){
  ## OSC function to perform a Cox regression and generate the plot
  coxph(Surv(OS_Months, OS_Status) ~ ecDNA + strata(Cancer_Type_Abbrev), data = data)
}
km_plot <- function(survObj,outfile){
  ## OSC function to perform a KM analysis and generate the plot
  survObj %>% 
   ggsurvfit(linewidth=0.5) +
   labs(x = 'Follow-up time (Months)',
        y = 'Overall Survival') +
   scale_color_manual(values = c('blue', 'red'),
                      labels = c('ecDNA-', 'ecDNA+')) +
   scale_fill_manual(values = c('blue', 'red'),
                     labels = c('ecDNA-', 'ecDNA+')) +
   scale_y_continuous(limits=c(0, 1))+
   add_censor_mark(size = .5, alpha = 1) +
   add_confidence_interval() +
   add_risktable(risktable_stats = "n.risk", size=2,
                 theme = theme_risktable_default(axis.text.y.size = 7,
                                    plot.title.size = 7)) +
   add_risktable_strata_symbol(size=4) + 
   theme_classic(base_size=7, base_family="Arial",) +
   theme(axis.text = element_text(size=7,colour="black"),
         legend.position = "bottom",
      #legend.text = element_text(size = 7),
      #legend.key.size = unit(0.75, "line"),
      #axis.text.x = element_text(size = 7),
      #axis.text.y = element_text(size = 7),
      #axis.title.x = element_text(size = 7),
      #axis.title.y = element_text(size = 7))
   )

  
  pdfName = paste(outfile, ".pdf", sep="")
  pngName = paste(outfile, ".png", sep="")
  svgName = paste(outfile, ".svg", sep = "")
  ggsave(path="../out", filename=pdfName, device="pdf", width=3, height=3.5, units='in')
  ggsave(path="../out", device="png", filename=pngName, width=3, height=3.5, units='in')
  ggsave(path="../out", device="svg", filename=svgName, width=3, height=3.5, units='in')
  
  return
}
```
#Read in combined cohort
```{r}
## OSC call load_survival_data here
dd <- load_survival_data("../data/combinedsurv.xlsx", "none")
# combinedsurv <- read_excel("../data/combinedsurv.xlsx")
```
#Generating data table for full cohort
```{r}
# dd <- combinedsurv %>%
#   mutate(ecDNA = factor(ecDNA_Status, labels = c('No','Yes')),
#          Cancer_Type = factor(Cancer_Type_Abbrev))
# var_label(dd) <- list(Cancer_Type = 'Cancer_Type_Abbrev')
```
# Cox regression for full cohort (for ecDNA status)
```{r}
## OSC call cox_plot here
m1 <- cox_plot(dd, outfile)
#m1
#m1 <- coxph(Surv(OS_Months, OS_Status) ~ ecDNA + strata(Cancer_Type_Abbrev), data = dd)
m1_unstrat <- coxph(Surv(OS_Months, OS_Status) ~ ecDNA + Cancer_Type_Abbrev, data = dd)
m1
m1_unstrat
coxZph <-cox.zph(m1_unstrat)
print(coxZph)

# KM by ecDNA status (not censored)
#km_plot(survfit2( Surv(OS_Months, OS_Status) ~ ecDNA_Status, data = dd), "km_surv_all")

# KM by ecDNA status censored at 5 years
km_plot(survfit2( Surv(OS_Months_5yrCensor, OS_Status_5yrCensor) ~ ecDNA_Status, data = dd), "km_surv_all_5year")
```
#Subset for cancer types that have at least one sample with ecDNA
```{r}
dd2 <- load_survival_data("../data/combinedsurv.xlsx", "ecDNA")
```
#Cox regression for subsetted cohort
```{r}
## OSC Call cox_plot here
m1 <- cox_plot(dd2, outfile)
#m1 <- coxph(Surv(OS_Months, OS_Status) ~ ecDNA_Status + strata(Cancer_Type_Abbrev), data = dd2)
m1

# Subset without rb and gg
dd3 <-load_survival_data("../data/combinedsurv.xlsx", "surv_cox")
m1_unstrat <- coxph(Surv(OS_Months, OS_Status) ~ ecDNA + Cancer_Type_Abbrev, data = dd3)
m1_unstrat
coxZph <-cox.zph(m1_unstrat)
print(coxZph)

# inline forest plot for cox regression
m1 %>%
   tbl_regression(
      exponentiate = TRUE,
      pvalue_fun = function(x) style_pvalue(x, digits = 2)
   ) %>%
   add_inline_forest_plot(
      spec_pointrange.args = list(
         vline = 1,
         xlim = c(0, 10)
      )
   )

# inline forest plot without rb and gg
m1_unstrat %>%
   tbl_regression(
      exponentiate = TRUE,
      pvalue_fun = function(x) style_pvalue(x, digits = 2)
   ) %>%
   add_inline_forest_plot(
      spec_pointrange.args = list(
         vline = 1,
         xlim = c(0, 10)
      )
   )

# KM by ecDNA status for subsetted cohort
# km_plot(survfit2( Surv(OS_Months, OS_Status) ~ ecDNA_Status, data = dd2 ), "km_surv_subset")

# KM by ecDNA status censored at 5 years for subsetting cohort
## OSC call km_plot here
km_plot(survfit2( Surv(OS_Months_5yrCensor, OS_Status_5yrCensor) ~ ecDNA_Status, data = dd2 ), "km_surv_subset_5year")
```
