---
title: "PedPanCancer_PairedSampleAnalysis"
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
library(dplyr)
library("stringr")
library(stringr)
library(naniar) #for replace with Nas function
library("survival")
library("survminer")
library(RColorBrewer)
library(janitor)
```
#Read in files
```{r}
na_strings <- c("NA", "n/a", "Not Available", "Not Reported")
```
#Read in CBTN
```{r}
CBTNbysample <- read_excel("/Users/sunitasridhar/Desktop/Research/pedpancan/cbtn/PedPanCancer_CBTNSurvAnalysisbySample.xlsx", na = na_strings)

#removing suffix from the Sample_ID column
CBTNbysample$`Sample ID`=str_remove(CBTNbysample$`Sample ID`,"\\_.*")
CBTNbysample$`Sample ID`=sub("^([^-]*-[^-]*).*", "\\1", CBTNbysample$`Sample ID`)
CBTNbysample$`Sample ID`=sub("-T", "", CBTNbysample$`Sample ID`)
CBTNbysamplefilter <- subset(CBTNbysample, duplicated(CBTNbysample$`Sample ID`))
CBTNbysamplecellline <- subset(CBTNbysample, SAMPLE_TYPE=="Derived Cell Line")
CBTNbysamplecelllinepatients <- subset(CBTNbysample, Patient_ID=="PT_KZ56XHJT" | Patient_ID=="PT_NK8A49X5" | Patient_ID=="PT_V1HNAC2Q" | Patient_ID=="PT_WGVEF96B" | Patient_ID=="PT_3AWKWXEV" | Patient_ID=="PT_4347ZBEX" | Patient_ID=="PT_C2D4JXS1" | Patient_ID=="PT_HNZNZ635" | Patient_ID=="PT_JNEV57VK" | Patient_ID=="PT_JSFBMK5V" | Patient_ID=="PT_KBFM551M" | Patient_ID=="PT_VAJN5QP8" | Patient_ID=="PT_VTM2STE3" | Patient_ID=="PT_Y5KY6KN9" | Patient_ID=="PT_Z4PJA6KT" | Patient_ID=="PT_VPEMAQBN")
CBTNbysamplecelllinepatientsfilter <- subset(CBTNbysamplecelllinepatients, select = c("Specimen_ID", "Patient_ID", "Cancer_Type", "ecDNA", "Sample ID", "CANCER_TYPE_DETAILED", "SAMPLE_TYPE","TUMOR_TYPE"))

#subsetting for desired columns
CBTNbysamplesubset <- subset(CBTNbysample, select = c("Specimen_ID", "Patient_ID", "ecDNA", "Cancer_Type", "TUMOR_TYPE"))
names(CBTNbysamplesubset) = c("Sample_ID", "Patient_ID", "ecDNA_status", "Cancer_Type_Abbrev", "Tumor_status")
CBTNbysamplesubset <- CBTNbysamplesubset[,c(1,2,4,3,5)]
#standardize tumor status
CBTNbysamplesubset$"Tumor_status"<-gsub("recurrence","secondary",as.character(CBTNbysamplesubset$"Tumor_status"))
CBTNbysamplesubset$"Tumor_status"<-gsub("progression","secondary",as.character(CBTNbysamplesubset$"Tumor_status"))
CBTNbysamplesubset$"Tumor_status"<-gsub("metastasis","secondary",as.character(CBTNbysamplesubset$"Tumor_status"))
CBTNbysamplesubset$"Tumor_status"<-gsub("Recurrence","secondary",as.character(CBTNbysamplesubset$"Tumor_status"))
CBTNbysamplesubset$"Tumor_status"<-gsub("Diagnosis","primary",as.character(CBTNbysamplesubset$"Tumor_status"))
CBTNbysamplesubset$"Tumor_status"<-gsub("Progressive Disease Post-Mortem","secondary",as.character(CBTNbysamplesubset$"Tumor_status"))
CBTNbysamplesubset$"Tumor_status"<-gsub("Progressive","secondary",as.character(CBTNbysamplesubset$"Tumor_status"))
```
#Read in SJ files
```{r}
SJsurv <- read_excel("/Users/sunitasridhar/Desktop/Research/pedpancan/stjude/survival_data/SJ_SurvivalAnalysis.xlsx", na = na_strings)
Mastersurv <- read_excel("/Users/sunitasridhar/Desktop/Research/pedpancan/stjude/survival_data/SJ_SurvivalMaster.xlsx", na = na_strings)
#remove all blank spaces in my excel sheets (one excel pressed Ctrl+space and then find and replace, replaced space with nothing)

#merging the SJ survival data and the ecDNA data
SJsurvmerged <- left_join(SJsurv, Mastersurv, by="Sample_ID")

#select only columns that are needed
SJsurvmergedfilter1 <- subset(SJsurvmerged, select = c("Sample_ID", "Patient_ID", "tumor_type", "ecDNA"))
names(SJsurvmergedfilter1) = c("Sample_ID", "Patient_ID", "Cancer_Type_Abbrev", "ecDNA_status")

#Create new column based on relapse/progression status
test <- str_split(SJsurvmergedfilter1$Sample_ID, "_", 2)
test1 <- matrix(unlist(test),ncol=2,byrow=T)
test1 <- data.frame(test1)
test2 <- test1$X2
test2 <- data.frame(test2)
SJsurvmergedfilter2 <- cbind(SJsurvmergedfilter1, test2)
names(SJsurvmergedfilter2) = c("Sample_ID", "Patient_ID", "Cancer_Type_Abbrev", "ecDNA_status", "Tumor_status")
SJsurvmergedfilter2$"Tumor_status"<-gsub("D","primary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("D1","primary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("D2","primary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("D3","primary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("E","secondary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("S","secondary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("R","secondary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("R1","secondary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("M1","secondary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("M8","secondary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("M","secondary",as.character(SJsurvmergedfilter2$"Tumor_status"))

SJsurvmergedfilter2$"Tumor_status"<-gsub("primary1", "primary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("primary2", "primary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("primary3", "primary",as.character(SJsurvmergedfilter2$"Tumor_status"))
SJsurvmergedfilter2$"Tumor_status"<-gsub("secondary1", "secondary",as.character(SJsurvmergedfilter2$"Tumor_status"))
```
#Merge CBTN and SJ files
```{r}
SJCBTNmerged <- rbind(SJsurvmergedfilter2, CBTNbysamplesubset)
SJCBTNmerged1 <- subset(SJCBTNmerged, Tumor_status == "secondary")
SJCBTNmerged2 <- subset(SJCBTNmerged1, ecDNA_status == "1")
SJCBTNmerged3 <- subset(SJCBTNmerged, ecDNA_status == "0")
SJCBTNmergedfilter <- subset(SJCBTNmerged, duplicated(SJCBTNmerged$Patient_ID))
length(unique(SJCBTNmergedfilter$Patient_ID))
SJCBTNmerged4 <- subset(CBTNbysample, )
```